[buildPlans.iosevka-murali]                         # <iosevka-custom> is your plan name
family = "Iosevka Murali"                           # Font menu family name
design = ["ss09", "expanded"] # Customize styles

[buildPlans.iosevka-murali-slab]
family = "Iosevka Murali Slab"
design = ["slab", "ss09", "expanded"]
